### ISSUE TITLE
ImportError: No module named _caffe

### ISSUE THREAD

**Issue by rsingh2083** [NVIDIAAICITYCHALLENGE/2018AICITY_MCPRL#3]
While running 

`python tools/car-faster.py --net vgg16`

I get error as  :--

```
Traceback (most recent call last):
  File "tools/car_faster.py", line 19, in <module>
    from fast_rcnn.test import im_detect
  File "/media/rsingh/My Passport/2018AICITY_MCPRL-master/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 16, in <module>
    import caffe
  File "/media/rsingh/My Passport/2018AICITY_MCPRL-master/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/media/rsingh/My Passport/2018AICITY_MCPRL-master/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: No module named _caffe
```

**Comment by jiayi-wei** [comment]
So, do you have caffe in your server
